#page title
page_title: Virtues Meditation # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6748882464 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Virtues Meditation # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Your Daily Path to Personal Growth & Inner Calm

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Matt Skoglund
your_link: https://MattSkoglund.github.io
your_city:
email_address: virtues.meditation@gmail.com
linkedin_username:
linkedin_company:
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
    - title: Daily Virtue Meditations
      description: Each day, unlock a new, inspiring meditation focused on a specific virtue – Wisdom, Courage, Justice, Temperance, and more. Curated content helps you apply profound insights to modern challenges.
      fontawesome_icon_name: sun

    - title: Guided Reflection & Journaling
      description: Capture your personal insights and track your personal development journey directly in your private journal.
      fontawesome_icon_name: book-open

    - title: Intuitive Meditation Timer
      description: Focus your practice with a clean, distraction-free timer, designed to help you build a consistent meditation habit.
      fontawesome_icon_name: stopwatch

    - title: Progress & History Tracking
      description: Visualize your journey with a comprehensive calendar view. Easily review past meditations and journal entries from any day, seeing your growth over time.
      fontawesome_icon_name: calendar-alt

    - title: Personalized Daily Reminders
      description: Set custom notifications to ensure you never miss your moment of peace and reflection, making consistency effortless.
      fontawesome_icon_name: bell

    - title: Seamless & Serene Experience
      description: Enjoy a beautifully designed, minimalist interface that promotes calm and focus, enhancing your mindfulness practice.
      fontawesome_icon_name: magic

    - title: No Distractions
      description: No ads and no data collection.
      fontawesome_icon_name: eye-slash

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#25292e"

link_color: "#A0522D"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#ffffff"
feature_text_color: "#ccc"

feature_icons_foreground_color: "#A0522D"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#22573B"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#ffffff"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - CNAME

collections:
    pages:
        output: true
        permalink: /:path/

# Markdown rendering
markdown: kramdown
